const PDFDocument = require("pdfkit")

exports.downloadReport = (req, res) => {

const doc = new PDFDocument()

res.setHeader(
"Content-Type",
"application/pdf"
)

res.setHeader(
"Content-Disposition",
'attachment; filename="SmartHire_Report.pdf"'
)

doc.pipe(res)

doc.fontSize(24)
.text("SmartHire AI Resume Report", {
align: "center"
})

doc.moveDown()

doc.fontSize(16)
.text("Candidate Name : Candidate")

doc.text("Resume Score : 85%")

doc.text("ATS Status : Eligible")

doc.moveDown()

doc.fontSize(18)
.text("Detected Skills")

doc.fontSize(14)
.text("• React")

doc.text("• Node.js")

doc.text("• MongoDB")

doc.text("• JavaScript")

doc.moveDown()

doc.fontSize(18)
.text("AI Suggestions")

doc.fontSize(14)
.text("• Learn Docker")

doc.text("• Learn AWS")

doc.text("• Improve Resume Summary")

doc.text("• Add Quantified Projects")

doc.moveDown()

doc.fontSize(18)
.text("Recommended Jobs")

doc.fontSize(14)
.text("• Frontend Developer")

doc.text("• MERN Developer")

doc.text("• Software Engineer")

doc.moveDown()

doc.fillColor("green")
.fontSize(20)
.text("Generated by SmartHire AI", {
align: "center"
})

doc.end()

}